name: keramieke
favicon: null
layout_spectrum: 0
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#21181d'
    - '#dcb7a5'
    - '#384b1d'
    - '#942710'
  brandStrength: 0.6875
  lightness: 0.2671509073115885
  saturation: 0.84250249247998
  rhythmicContrast: 0.05467685707844794
purpose: []
